name: gmso-dev
channels:
  - conda-forge
dependencies:
  - numpy
  - sympy
  - unyt >= 2.4
  - boltons
  - lxml
  - pydantic < 1.9.0
  - networkx
  - pytest
  - mbuild >= 0.11.0
  - openbabel >= 3.0.0
  - foyer >= 0.9.4
  - gsd >= 2.0
  - parmed >= 3.4.3
  - pytest-cov
  - codecov
  - bump2version
  - matplotlib
  - ipywidgets
  - ele >= 0.2.0
  - pre-commit
  - python=3.9
