name: gmso
channels:
  - conda-forge
dependencies:
  - python>=3.11, <=3.14
  - boltons
  - numpy>=2.0,<2.3
  - sympy
  - unyt>=2.9.5
  - boltons
  - lxml
  - pydantic>=2
  - networkx
  - ele>=0.2.0
  - foyer>=0.11.3
  - forcefield-utilities>=0.4.0
  - symengine
  - python-symengine
