name: gmso-dev
channels:
  - conda-forge
dependencies:
  - python>=3.9,<=3.12
  - boltons
  - numpy=1.26.4
  - sympy
  - unyt>=2.9.5
  - boltons
  - lxml
  - pydantic>=2
  - networkx
  - pytest
  - mbuild>=1.1
  - openbabel>=3.0.0
  - foyer>=0.11.3
  - forcefield-utilities>=0.2.1
  - gsd>=2.9
  - parmed>=3.4.3
  - pytest-cov
  - codecov
  - bump2version
  - matplotlib
  - ipywidgets
  - ele>=0.2.0
  - pre-commit
  - pandas
  - symengine
  - python-symengine
  - hoomd
  - importlib_resources
