name: gmso
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - numpy=1.24.2
  - sympy
  - unyt<=2.9.2
  - boltons
  - lxml
  - pydantic<2.0
  - networkx
  - ele>=0.2.0
  - foyer>=0.11.3
  - forcefield-utilities>=0.2.1
  - symengine
  - python-symengine
