name: gmso
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - boltons
  - numpy
  - sympy
  - unyt
  - boltons
  - lxml
  - pydantic
  - networkx
  - ele>=0.2.0
  - foyer>=0.11.3
  - forcefield-utilities>=0.2.1
  - symengine
  - python-symengine
  - importlib_resources
